#
# This file is autogenerated during plugin quickstart and overwritten during
# plugin makedist. DO NOT CHANGE IT if you plan to use plugin makedist to update 
# the distribution.
#

from setuptools import setup, find_packages

kwargs = {'author': '',
 'author_email': '',
 'classifiers': ['Intended Audience :: Science/Research',
                 'Topic :: Scientific/Engineering'],
 'description': '',
 'download_url': '',
 'entry_points': u'[openmdao.component]\nmama.subsystem.Summation=mama.subsystem:Summation\nmama.subsystems.TPS=mama.subsystems:TPS\nmama.tank.Tank=mama.tank:Tank\nmama.maneuver.Maneuver=mama.maneuver:Maneuver\nmama.subsystems.FuelSubsystem=mama.subsystems:FuelSubsystem\nmama.spacecraft.Spacecraft=mama.spacecraft:Spacecraft\nmama.mission.Mission=mama.mission:Mission\nmama.maneuver.Orbit=mama.maneuver:Orbit\nmama.subsystems.MMOD=mama.subsystems:MMOD\nmama.subsystem.Subsystem=mama.subsystem:Subsystem\nmama.mission.Phase=mama.mission:Phase\nmama.spacecraft.Stage=mama.spacecraft:Stage\nmama.subsystems.CargoSubsystem=mama.subsystems:CargoSubsystem\n\n[openmdao.container]\nmama.subsystem.Summation=mama.subsystem:Summation\nmama.subsystems.TPS=mama.subsystems:TPS\nmama.tank.Tank=mama.tank:Tank\nmama.maneuver.Maneuver=mama.maneuver:Maneuver\nmama.subsystems.FuelSubsystem=mama.subsystems:FuelSubsystem\nmama.spacecraft.Spacecraft=mama.spacecraft:Spacecraft\nmama.mission.Mission=mama.mission:Mission\nmama.maneuver.Orbit=mama.maneuver:Orbit\nmama.subsystems.MMOD=mama.subsystems:MMOD\nmama.subsystem.Subsystem=mama.subsystem:Subsystem\nmama.mission.Phase=mama.mission:Phase\nmama.spacecraft.Stage=mama.spacecraft:Stage\nmama.subsystems.CargoSubsystem=mama.subsystems:CargoSubsystem',
 'include_package_data': True,
 'install_requires': ['openmdao.main'],
 'keywords': ['openmdao'],
 'license': '',
 'maintainer': '',
 'maintainer_email': '',
 'name': 'mama',
 'package_data': {'mama': []},
 'package_dir': {'': 'src'},
 'packages': ['mama', 'mama.test'],
 'url': '',
 'version': '0.1',
 'zip_safe': False}


setup(**kwargs)

